// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: favorites.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :one
INSERT INTO favorites (user_id, product_id)
VALUES ($1, $2)
RETURNING id, user_id, product_id, created_at
`

type AddFavoriteParams struct {
	UserID    pgtype.UUID
	ProductID pgtype.UUID
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) (Favorite, error) {
	row := q.db.QueryRow(ctx, addFavorite, arg.UserID, arg.ProductID)
	var i Favorite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.CreatedAt,
	)
	return i, err
}

const clearFavoritesByUser = `-- name: ClearFavoritesByUser :exec
DELETE FROM favorites
WHERE user_id = $1
`

func (q *Queries) ClearFavoritesByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearFavoritesByUser, userID)
	return err
}

const countFavoritesByProduct = `-- name: CountFavoritesByProduct :many
SELECT product_id, COUNT(*) AS favorite_count
FROM favorites
GROUP BY product_id
ORDER BY favorite_count DESC
LIMIT $1
`

type CountFavoritesByProductRow struct {
	ProductID     pgtype.UUID
	FavoriteCount int64
}

func (q *Queries) CountFavoritesByProduct(ctx context.Context, limit int32) ([]CountFavoritesByProductRow, error) {
	rows, err := q.db.Query(ctx, countFavoritesByProduct, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountFavoritesByProductRow
	for rows.Next() {
		var i CountFavoritesByProductRow
		if err := rows.Scan(&i.ProductID, &i.FavoriteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFavoritesByUser = `-- name: CountFavoritesByUser :one
SELECT COUNT(*) FROM favorites
WHERE user_id = $1
`

func (q *Queries) CountFavoritesByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoritesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFavoritesByProduct = `-- name: DeleteFavoritesByProduct :exec
DELETE FROM favorites
WHERE product_id = $1
`

func (q *Queries) DeleteFavoritesByProduct(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFavoritesByProduct, productID)
	return err
}

const getFavoriteByUserAndProduct = `-- name: GetFavoriteByUserAndProduct :one
SELECT id, user_id, product_id, created_at FROM favorites
WHERE user_id = $1 AND product_id = $2
LIMIT 1
`

type GetFavoriteByUserAndProductParams struct {
	UserID    pgtype.UUID
	ProductID pgtype.UUID
}

func (q *Queries) GetFavoriteByUserAndProduct(ctx context.Context, arg GetFavoriteByUserAndProductParams) (Favorite, error) {
	row := q.db.QueryRow(ctx, getFavoriteByUserAndProduct, arg.UserID, arg.ProductID)
	var i Favorite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.CreatedAt,
	)
	return i, err
}

const listFavoritesByUser = `-- name: ListFavoritesByUser :many
SELECT id, user_id, product_id, created_at FROM favorites
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListFavoritesByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListFavoritesByUser(ctx context.Context, arg ListFavoritesByUserParams) ([]Favorite, error) {
	rows, err := q.db.Query(ctx, listFavoritesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Favorite
	for rows.Next() {
		var i Favorite
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites
WHERE user_id = $1 AND product_id = $2
`

type RemoveFavoriteParams struct {
	UserID    pgtype.UUID
	ProductID pgtype.UUID
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.ProductID)
	return err
}
