// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: alerts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAlertsByUser = `-- name: CountAlertsByUser :one
SELECT COUNT(*) FROM alerts
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountAlertsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAlertsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllAlerts = `-- name: CountAllAlerts :one
SELECT COUNT(*) FROM alerts
WHERE deleted_at IS NULL
`

func (q *Queries) CountAllAlerts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllAlerts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (user_id, product_id, type, threshold)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, product_id, type, threshold, is_active, triggered_at, deleted_at, created_at, updated_at
`

type CreateAlertParams struct {
	UserID    pgtype.UUID
	ProductID pgtype.UUID
	Type      string
	Threshold pgtype.Numeric
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.UserID,
		arg.ProductID,
		arg.Type,
		arg.Threshold,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Type,
		&i.Threshold,
		&i.IsActive,
		&i.TriggeredAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAlertsForProduct = `-- name: GetActiveAlertsForProduct :many
SELECT id, user_id, product_id, type, threshold, is_active, triggered_at, deleted_at, created_at, updated_at FROM alerts
WHERE product_id = $1
  AND type = $2
  AND is_active = true
  AND deleted_at IS NULL
`

type GetActiveAlertsForProductParams struct {
	ProductID pgtype.UUID
	Type      string
}

func (q *Queries) GetActiveAlertsForProduct(ctx context.Context, arg GetActiveAlertsForProductParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, getActiveAlertsForProduct, arg.ProductID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Type,
			&i.Threshold,
			&i.IsActive,
			&i.TriggeredAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlertByID = `-- name: GetAlertByID :one
SELECT id, user_id, product_id, type, threshold, is_active, triggered_at, deleted_at, created_at, updated_at FROM alerts
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetAlertByID(ctx context.Context, id pgtype.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlertByID, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Type,
		&i.Threshold,
		&i.IsActive,
		&i.TriggeredAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlertByIDAndUser = `-- name: GetAlertByIDAndUser :one
SELECT id, user_id, product_id, type, threshold, is_active, triggered_at, deleted_at, created_at, updated_at FROM alerts
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetAlertByIDAndUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetAlertByIDAndUser(ctx context.Context, arg GetAlertByIDAndUserParams) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlertByIDAndUser, arg.ID, arg.UserID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Type,
		&i.Threshold,
		&i.IsActive,
		&i.TriggeredAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlertsByUser = `-- name: ListAlertsByUser :many
SELECT id, user_id, product_id, type, threshold, is_active, triggered_at, deleted_at, created_at, updated_at FROM alerts
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAlertsByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListAlertsByUser(ctx context.Context, arg ListAlertsByUserParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Type,
			&i.Threshold,
			&i.IsActive,
			&i.TriggeredAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsByUserFiltered = `-- name: ListAlertsByUserFiltered :many
SELECT id, user_id, product_id, type, threshold, is_active, triggered_at, deleted_at, created_at, updated_at FROM alerts
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($3::boolean IS NULL OR is_active = $3)
  AND ($4::varchar IS NULL OR type = $4)
ORDER BY created_at DESC
LIMIT $2 OFFSET $5
`

type ListAlertsByUserFilteredParams struct {
	UserID  pgtype.UUID
	Limit   int32
	Column3 bool
	Column4 string
	Offset  int32
}

func (q *Queries) ListAlertsByUserFiltered(ctx context.Context, arg ListAlertsByUserFilteredParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsByUserFiltered,
		arg.UserID,
		arg.Limit,
		arg.Column3,
		arg.Column4,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Type,
			&i.Threshold,
			&i.IsActive,
			&i.TriggeredAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAlerts = `-- name: ListAllAlerts :many
SELECT id, user_id, product_id, type, threshold, is_active, triggered_at, deleted_at, created_at, updated_at FROM alerts
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllAlertsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAllAlerts(ctx context.Context, arg ListAllAlertsParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAllAlerts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Type,
			&i.Threshold,
			&i.IsActive,
			&i.TriggeredAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAlert = `-- name: SoftDeleteAlert :exec
UPDATE alerts
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteAlertParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) SoftDeleteAlert(ctx context.Context, arg SoftDeleteAlertParams) error {
	_, err := q.db.Exec(ctx, softDeleteAlert, arg.ID, arg.UserID)
	return err
}

const toggleAlert = `-- name: ToggleAlert :one
UPDATE alerts
SET is_active = $2, triggered_at = CASE WHEN $2 THEN NULL ELSE triggered_at END, updated_at = NOW()
WHERE id = $1 AND user_id = $3 AND deleted_at IS NULL
RETURNING id, user_id, product_id, type, threshold, is_active, triggered_at, deleted_at, created_at, updated_at
`

type ToggleAlertParams struct {
	ID       pgtype.UUID
	IsActive bool
	UserID   pgtype.UUID
}

func (q *Queries) ToggleAlert(ctx context.Context, arg ToggleAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, toggleAlert, arg.ID, arg.IsActive, arg.UserID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Type,
		&i.Threshold,
		&i.IsActive,
		&i.TriggeredAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const triggerAlert = `-- name: TriggerAlert :one
UPDATE alerts
SET is_active = false, triggered_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, product_id, type, threshold, is_active, triggered_at, deleted_at, created_at, updated_at
`

func (q *Queries) TriggerAlert(ctx context.Context, id pgtype.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, triggerAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Type,
		&i.Threshold,
		&i.IsActive,
		&i.TriggeredAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAlert = `-- name: UpdateAlert :one
UPDATE alerts
SET type = $2, threshold = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $4 AND deleted_at IS NULL
RETURNING id, user_id, product_id, type, threshold, is_active, triggered_at, deleted_at, created_at, updated_at
`

type UpdateAlertParams struct {
	ID        pgtype.UUID
	Type      string
	Threshold pgtype.Numeric
	UserID    pgtype.UUID
}

func (q *Queries) UpdateAlert(ctx context.Context, arg UpdateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, updateAlert,
		arg.ID,
		arg.Type,
		arg.Threshold,
		arg.UserID,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Type,
		&i.Threshold,
		&i.IsActive,
		&i.TriggeredAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
