// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	ProductID   pgtype.UUID
	Type        string
	Threshold   pgtype.Numeric
	IsActive    bool
	TriggeredAt pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type AlertOutbox struct {
	ID        pgtype.UUID
	AlertID   pgtype.UUID
	EventType string
	Payload   []byte
	Published bool
	CreatedAt pgtype.Timestamptz
}
