// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OtpCode struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	CodeHash    string
	Type        string
	Attempts    int16
	MaxAttempts int16
	Used        bool
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type OtpRateLimit struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Type        string
	SentCount   int16
	WindowStart pgtype.Timestamptz
}

type PasswordResetToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	Used      bool
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
