// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: otp.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOTPCode = `-- name: CreateOTPCode :one
INSERT INTO otp_codes (user_id, code_hash, type, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, code_hash, type, attempts, max_attempts, used, expires_at, created_at
`

type CreateOTPCodeParams struct {
	UserID    pgtype.UUID
	CodeHash  string
	Type      string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateOTPCode(ctx context.Context, arg CreateOTPCodeParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTPCode,
		arg.UserID,
		arg.CodeHash,
		arg.Type,
		arg.ExpiresAt,
	)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Type,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveOTPCode = `-- name: GetActiveOTPCode :one
SELECT id, user_id, code_hash, type, attempts, max_attempts, used, expires_at, created_at
FROM otp_codes
WHERE user_id = $1 AND type = $2 AND used = false AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveOTPCodeParams struct {
	UserID pgtype.UUID
	Type   string
}

func (q *Queries) GetActiveOTPCode(ctx context.Context, arg GetActiveOTPCodeParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getActiveOTPCode, arg.UserID, arg.Type)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Type,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOTPRateLimit = `-- name: GetOTPRateLimit :one
SELECT id, user_id, type, sent_count, window_start
FROM otp_rate_limits
WHERE user_id = $1 AND type = $2
`

type GetOTPRateLimitParams struct {
	UserID pgtype.UUID
	Type   string
}

func (q *Queries) GetOTPRateLimit(ctx context.Context, arg GetOTPRateLimitParams) (OtpRateLimit, error) {
	row := q.db.QueryRow(ctx, getOTPRateLimit, arg.UserID, arg.Type)
	var i OtpRateLimit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.SentCount,
		&i.WindowStart,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :one
UPDATE otp_codes
SET attempts = attempts + 1
WHERE id = $1
RETURNING id, user_id, code_hash, type, attempts, max_attempts, used, expires_at, created_at
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id pgtype.UUID) (OtpCode, error) {
	row := q.db.QueryRow(ctx, incrementOTPAttempts, id)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Type,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateAllOTPCodes = `-- name: InvalidateAllOTPCodes :exec
UPDATE otp_codes SET used = true WHERE user_id = $1 AND type = $2 AND used = false
`

type InvalidateAllOTPCodesParams struct {
	UserID pgtype.UUID
	Type   string
}

func (q *Queries) InvalidateAllOTPCodes(ctx context.Context, arg InvalidateAllOTPCodesParams) error {
	_, err := q.db.Exec(ctx, invalidateAllOTPCodes, arg.UserID, arg.Type)
	return err
}

const markOTPUsed = `-- name: MarkOTPUsed :exec
UPDATE otp_codes SET used = true WHERE id = $1
`

func (q *Queries) MarkOTPUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOTPUsed, id)
	return err
}

const resetOTPRateLimit = `-- name: ResetOTPRateLimit :exec
UPDATE otp_rate_limits SET sent_count = 1, window_start = NOW()
WHERE user_id = $1 AND type = $2
`

type ResetOTPRateLimitParams struct {
	UserID pgtype.UUID
	Type   string
}

func (q *Queries) ResetOTPRateLimit(ctx context.Context, arg ResetOTPRateLimitParams) error {
	_, err := q.db.Exec(ctx, resetOTPRateLimit, arg.UserID, arg.Type)
	return err
}

const upsertOTPRateLimit = `-- name: UpsertOTPRateLimit :one
INSERT INTO otp_rate_limits (user_id, type, sent_count, window_start)
VALUES ($1, $2, 1, NOW())
ON CONFLICT (user_id, type) DO UPDATE
SET sent_count = otp_rate_limits.sent_count + 1
RETURNING id, user_id, type, sent_count, window_start
`

type UpsertOTPRateLimitParams struct {
	UserID pgtype.UUID
	Type   string
}

func (q *Queries) UpsertOTPRateLimit(ctx context.Context, arg UpsertOTPRateLimitParams) (OtpRateLimit, error) {
	row := q.db.QueryRow(ctx, upsertOTPRateLimit, arg.UserID, arg.Type)
	var i OtpRateLimit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.SentCount,
		&i.WindowStart,
	)
	return i, err
}
