export const endpoints = {
  auth: {
    login: "/auth/login",
    google: "/auth/google",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    logoutAll: "/auth/logout-all",
  },
  users: {
    signup: "/users/signup",
    me: "/users/me",
    changePassword: "/users/me/password",
    setPassword: "/users/me/password/set",
    deleteMe: "/users/me",
    list: "/users",
    detail: (id: string) => `/users/${encodeURIComponent(id)}`,
    ban: (id: string) => `/users/${encodeURIComponent(id)}/ban`,
    role: (id: string) => `/users/${encodeURIComponent(id)}/role`,
  },
  otp: {
    emailSend: "/otp/email/send",
    emailVerify: "/otp/email/verify",
    passwordResetSend: "/otp/password-reset/send",
    passwordResetVerify: "/otp/password-reset/verify",
    passwordResetApply: "/otp/password-reset/apply",
    login2faVerify: "/otp/2fa/login/verify",
    enable2fa: "/otp/2fa/enable",
    enable2faVerify: "/otp/2fa/enable/verify",
    disable2fa: "/otp/2fa/disable",
    disable2faVerify: "/otp/2fa/disable/verify",
  },
  favorites: {
    collection: "/favorites",
    clear: "/favorites/all",
    item: (productId: string) => `/favorites/${encodeURIComponent(productId)}`,
    popular: "/admin/favorites/popular",
  },
  alerts: {
    collection: "/alerts",
    item: (id: string) => `/alerts/${encodeURIComponent(id)}`,
    toggle: (id: string) => `/alerts/${encodeURIComponent(id)}/toggle`,
    admin: "/admin/alerts",
  },
  gouvernorats: "/gouvernorats",
} as const;
